### ISSUE TITLE
Speeding up pyparsing

### ISSUE THREAD

**Issue by ptmcg** [mwganson/Parametric_Curve_FP#5]
If you are finding pyparsing to be slow, you can try enabling packrat cacheing:

    pyparsing.ParserElement.enablePackrat()

Other performance tips can be found on the pyparsing wiki: https://github.com/pyparsing/pyparsing/wiki/Performance-Tips 

You might also find some features in the pyparsing spinoff `plusminus` interesting for your application.

Congrats on your application, I'll add you to the "Who's Using Pyparsing?" list on the wiki home page!

**Comment by mwganson** [comment]
Thanks, Paul.

With this change my profiler gives these results:

1 features are touched
Generating execution order...
Number of features to execute: 1
Execution order:
    ParametricCurve
Recomputing... (time in seconds, label)
	3.8738155364990234	ParametricCurve

Without it:

1 features are touched
Generating execution order...
Number of features to execute: 1
Execution order:
    ParametricCurve
Recomputing... (time in seconds, label)
	1.7391467094421387	ParametricCurve

Caching seems to actually slow things down, at least in this particular test.

Extending the above by a factor of 10 shows similar results.  Without the caching about 17 seconds compared to about 38 seconds with caching.

Code change:

```
from pyparsing import (
    Literal,
    Word,
    Group,
    Forward,
    alphas,
    alphanums,
    Regex,
    ParseException,
    CaselessKeyword,
    Suppress,
    delimitedList,
#    ParserElement,
)
import math
import operator

#ParserElement.enablePackrat()
exprStack = []
```

The lines that are commented out are the ones that were added for the test.  The 'with' test has them uncommented and the 'without' test has them commented out.

**Comment by ptmcg** [comment]
Thanks for giving it a shot - packrat is not a sure thing, but it often helps with recursive parsers. (Though come to think of it, it is most helpful with the `infixNotation`-based arithmetic parsers, and you have based yours off of the older `fourFn.py`.)

It would be interesting to write an LR version of `fourFn.py` and compare for code complexity and performance.

(I'm assuming you are using a recent version of pyparsing - packrat got a huge improvement/rewrite back around 2.3.)

**Comment by mwganson** [comment]
I'm using the version bundled with FreeCAD.

>>> import pyparsing
>>> pyparsing.__version__
'2.4.7'
