### ISSUE TITLE
update from spreadsheet not working for d1, d2, ...

### ISSUE THREAD

**Issue by mike-554** [mwganson/Parametric_Curve_FP#9]
Hi,

Thanks for providing this great tool!

I was stumbling over a problem when using a spreadsheet for variables d1, d2, etc. After recalculating the curve, the value for d1 ended up in d1 and in d2. I believe that the reason is a bug in updateFromSpreadsheet(self,fp):

        dd=0
        k = "d"+str(dd+1)
        new_d = []
        while hasattr(fp.Spreadsheet,k):
            new_d.append(str(getattr(fp.Spreadsheet,k)))
            k = "d"+str(dd+1)
            dd += 1

Here, "dd" should be incremented before the new value is asigned to "k", i.e. the last two lines should be the other way round. 

Best,
Mike

**Comment by mwganson** [comment]
I have updated to version 0.2022.12.16.  Please update and test.  Thanks.

**Comment by mike-554** [comment]
Excellent! Works fine now. Thank you!
